name: Team awesome's approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: It is now approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPOVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "APPROVED!"
